# Generated by Django 5.2.6 on 2025-11-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemodel',
            name='user',
        ),
    ]
